version: '3.8'

services:
  postgres:
    image: postgres:latest 
    container_name: postgres-container 
    environment:
      POSTGRES_PASSWORD: yourpassword  
      POSTGRES_USER: postgres       
      POSTGRES_DB: calculator_db     
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data  
    restart: unless-stopped  

volumes:
  postgres_data: 