#!/bin/bash

function print-dir {

    echo "Total number of folders (including all nested ones) = $(find $1 -type d 2> /dev/null | wc -l)"
    echo "TOP 5 folders of maximum size arranged in descending order (path and size):"
    du -h --max-depth=1 --block-size=1M  $1 2>/dev/null | sort -hr | head -n 5 | awk '{print NR " - " $2 ", " $1 " MB"}'
    
    echo "Total number of files = $(find $1 -type f 2> /dev/null | wc -l)"
    
    conf_count=$(find $1 -type f -name "*.conf" 2> /dev/null| wc -l)
    txt_count=$(find $1 -type f -name "*.txt" 2> /dev/null| wc -l)
    exe_count=$(find $1 -type f -executable 2> /dev/null| wc -l)
    log_count=$(find $1 -type f -name "*.log" 2> /dev/null| wc -l)
    archive_count=$(find $1 -type f \( -iname "*tar" -o -iname "*.gz" -o -iname "*.zip" \) 2> /dev/null| wc -l)
    symlink_count=$(find $1 -type l 2> /dev/null| wc -l)
    
    echo "Number of:"
    echo "Configuration files (with the .conf extension) = $conf_count"
    echo "Text files = $txt_count"
    echo "Executable files = $exe_count"
    echo "Log files ( with the extension .log) = $log_count"
    echo "Archive files = $archive_count"
    echo "Symbolic links = $symlink_count"

    echo "TOP 10 files of maximum size arranged in descending order (path, size and type): "
    find $1 -type f -exec du -b {} + 2>/dev/null | sort -rh | head -n 10 | nl -v 1 | while read index size file; do
        file_type=$(file --mime-type -b "$file")
        size_human=$(numfmt --to=iec $size)
        echo "$index - $file, $size_human, $file_type"
    done

    echo "TOP 10 executable files of the maximum size arranged in descending order (path, size and MD5 hash of file): "
    find $1 -type f -executable -exec du -b {} + 2>/dev/null | sort -rh | head -n 10 | nl -v 1 | while read index size file; do
        md5_hash=$(md5sum "$file" | awk '{print $1}') 
        size_human=$(numfmt --to=iec $size)
        echo "$index - $file, $size_human, $md5_hash"
    done

}
