#!/bin/bash

function print-params {
    echo "HOSTNAME = $(hostname)"
    echo "TIMEZONE = $(timedatectl | grep 'Time zone' | awk '{print $3, $4, $5}')"
    echo "USER = $(whoami)"
    echo "OS = $(uname -sr | awk -F "." '{print $1"."$2}')"
    echo "DATE = $(date '+%d %b %Y %H:%M:%S')"
    echo "UPTIME = $(uptime -p)"
    echo "UPTIME_SEC = $(awk '{print $1}' /proc/uptime)"
    echo "IP = $(hostname -I | awk '{print $1}')"
    echo "MASK = $(ip a | grep $(hostname -I | awk '{print $1}') | awk '{print $4}')"
    echo "GATEWAY = $(ip r | grep default | awk '{print $3}')"
    echo "RAM_TOTAL = $(free -m | awk '/Mem:/ {printf "%.3f GB", $2/1024}')"
    echo "RAM_USED = $(free -m | awk '/Mem:/ {printf "%.3f GB", $3/1024}')"
    echo "RAM_FREE = $(free -m | awk '/Mem:/ {printf "%.3f GB", $4/1024}')"
    echo "SPACE_ROOT = $(df / | awk '/\// {printf "%.2f MB", $2/1024}')"
    echo "SPACE_ROOT_USED = $(df / | awk '/\// {printf "%.2f MB", $3/1024}')"
    echo "SPACE_ROOT_FREE = $(df / | awk '/\// {printf "%.2f MB", $4/1024}')"
}
